### ISSUE TITLE
Mark as watched button

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#1]
Add a button that marks a video watched in the subscriptions feed

**Comment by Dermott7** [comment]
Hey, any progress?

**Comment by OsaSoft** [comment]
Hey @Dermott7 , sorry I havent had time as Im currently travelling. I should be able to get back to development once October starts though. First planned are some bugs - mainly that in YouTube's dark theme it doesn't look good, then this button and after that other stuff

**Comment by Dermott7** [comment]
Cool, good to know. Can't wait for updates! The only issue I have on dark theme is that "hide watched" button on bottom is well visible. And addon does not always works but refreshing fixes the problem.

**Comment by Dermott7** [comment]
I'm still waiting for that feature, any ETA?

**Comment by OsaSoft** [comment]
@Dermott7 hey, sorry for that. Ive been busy with work and my thesis, so Ive only made small changes to things that broke how the plugin worked (like when youtube decided to load the 'watched' status after the page loaded) and have personally just been using youtube's 'Hide' button instead. This is definitely the next thing I have to do, but itll take quite a bit of work

**Comment by OsaSoft** [comment]
as for an ETA, I would really like to get this feature before christmas, but not 100% sure ill be able to

**Comment by OsaSoft** [comment]
Hey all. Im really sorry for being away for so long. I did do a little update here and there when necesary, but didnt have time to get into anything bigger.
Last couple of days however Ive had a bit of free time and managed to get some stuff done, one of which is a Chrome version of the extension (link in description).

Anyway, regarding the topic of this Issue: Ive managed to make some progress on a Mark as watched button, and Im hopeful Ill be able to push out a working version by the end of the week (probably wont be v1 still, since that also needs Issues #2 and #6 finished). So yay, fingers crossed?

**Comment by Dermott7** [comment]
Yay, fingers crossed then.

**Comment by OsaSoft** [comment]
Just finished the feature and posted onto Chrome and Firefox extension stores. Update should be rolling out to users shortly.
