### ISSUE TITLE
Adding new feature - create a new subscriptions section on page, of channels, for their old videos, on regular intervals 

### ISSUE THREAD

**Issue by kleenkanteen** [OsaSoft/youtube-better-subscriptions#101]
I was considering making a chrome extension for this idea, but first searched the current solutions made. There seems to be no extension that are maintained with this idea, but 2 other youtube extensions exist, this and Pocket tube, https://chrome.google.com/webstore/detail/pockettube-youtube-subscr/kdmnjgijlmjgmimahnillepgcgeemffb?hl=en. Pocket tube is a lot more feature rich, but different than what I was aiming for. And Pocket tube is not open source. This is also different, but it has the nice feature of removing watched videos, and I was wondering that I could build off of that instead of starting from scratch. The name is youtube better subscriptions, so it could use more features to suit the name. 

There is also this other extension here: https://www.mrfdev.com/enhancer-for-youtube which is very nice, I use it to make all videos in theater mode, actually almost fullscreen mode taking the whole browser space, and to hide the sidebar videos on the right. But even that doesn't have the idea I want.

Do you approve of this idea? Then I can start coding it.

**Comment by OsaSoft** [comment]
Hi. Not exactly sure what you mean. I have in plan to create a completely new subs feed improving greatly on the YT ui, which isnt great, but its something that i probably wont get around to in a loooong time 😅 https://github.com/OsaSoft/youtube-better-subscriptions/issues/30 . I guess that would be kind of similar to what pocket tube does. I also use enhancer for youtube btw 😄 its a great extension.

If you'd like to elaborate a bit on your idea we could probably collabolare and on it and add it as a part of this extension, but youre of course also free to just fork this and create your own one, as long as its also open source (per the gpl license this uses) :)
If you do, be sure to ping me with the link, as it sounds really interesting!

**Comment by kleenkanteen** [comment]
So the current subscriptions only shows a channel's new videos. Say you want to see a channel's old videos on a regular basis, maybe it's a good channel but it stopped uploading, or maybe you want to catch up with their past vids. You could do this manually but this would mean remembering every single channel, scrolling to the bottom of their videos, etc. But say there was a button you could click that could show you their oldest unwatched video, every week, or a specific interval. And these old videos would show up in the subscriptions page, but say under a section called "past videos". I could fork but tbh I'd prefer working together, it could be a sizeable project. Does that make sense?

**Comment by kleenkanteen** [comment]
@OsaSoft ^

**Comment by skoll43** [comment]
> Hi. Not exactly sure what you mean. I have in plan to create a completely new subs feed improving greatly on the YT ui, which isnt great, but its something that i probably wont get around to in a loooong time 😅 #30 . I guess that would be kind of similar to what pocket tube does. I also use enhancer for youtube btw 😄 its a great extension.
> 
> If you'd like to elaborate a bit on your idea we could probably collabolare and on it and add it as a part of this extension, but youre of course also free to just fork this and create your own one, as long as its also open source (per the gpl license this uses) :)
> If you do, be sure to ping me with the link, as it sounds really interesting!
hey, just wanted to say i love your piece of software man, i LOVE YOU haha

**Comment by kleenkanteen** [comment]
Closing because no reply.
