### ISSUE TITLE
Refreshing subscribtion feed causes weird bugs

### ISSUE THREAD

**Issue by Dermott7** [OsaSoft/youtube-better-subscriptions#104]
Hey, 
First of all, great addon, it's a must have for me to enjoy my time on youtube.

Few days ago I noticed that youtube started acting mega weird - whenever I typed something into search bar to find videos, the youtube kinda refreshes itself after 1-2 seconds and replaces videos with less accurate search results. It's very annoying, especially if I want to rewatch video I know - I'm typing its name, it's there, but seconds after its gone and replaced by other videos.

Today I found out that disabling and enabling addon fixes this issue, but not for long, because refreshing subscription feed is quite often. I'm using other YT related addon: PocketTube: Youtube Subscription Manager. I've tried to disable it and check again, unfortunately, it looks like your addon causes it :/

Another bug that appears after refreshing tab: the UI in subscription feed duplicates, so there's two sets of buttons and both of them work, again, restarting addon fixes this.

I'm using mozilla 97.0.1 (64 bits) and among PocketTube other addons such as Dark Reader, some Netflix related.

**Comment by OsaSoft** [comment]
Hey, thanks for the kind words and reaching out.
Ive also noticed the duplicate UI on my side, but not the refreshing issue. Sadly I havent had time to touch this project in quite a while now, but Ill try to take a look as soon as I can

**Comment by OsaSoft** [comment]
Can you enable logging in the addon settings and copy over the logs from the console (open the console with ctrl+shift+J) when this happens please?

**Comment by Dermott7** [comment]
I turned off and on your addon to start completely clean. Once youtube refreshed my searching result I checked console and this is what I got:

00:37:59.005
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
2 [index.js:4937](moz-extension://7dc32c54-ae55-472c-98b7-418dd335f71d/inject/index.js)
    sendMessage moz-extension://7dc32c54-ae55-472c-98b7-418dd335f71d/inject/[index.js:4937](moz-extension://7dc32c54-ae55-472c-98b7-418dd335f71d/inject/index.js)
00:38:00.166
Promise resolved while context is inactive
5 index.js:4937
    sendMessage moz-extension://7dc32c54-ae55-472c-98b7-418dd335f71d/inject/index.js:4937
00:38:00.167
sendRemoveListener on closed conduit danabok16@gmail.com.15805479649283 [ConduitsChild.jsm:112](resource://gre/modules/ConduitsChild.jsm)
    _send resource://gre/modules/ConduitsChild.jsm:112
    _send self-hosted:1287
    removeListener resource://gre/modules/ExtensionChild.jsm:670
    removeListener resource://gre/modules/ExtensionChild.jsm:905
    onChanged chrome://extensions/content/child/ext-storage.js:332
    removeListener resource://gre/modules/ExtensionCommon.jsm:2544
    revoke resource://gre/modules/ExtensionCommon.jsm:2566
    close resource://gre/modules/ExtensionCommon.jsm:2571
    unload resource://gre/modules/ExtensionCommon.jsm:892
    close resource://gre/modules/ExtensionContent.jsm:935
    destroyed resource://gre/modules/ExtensionContent.jsm:1011
    observe resource://gre/modules/ExtensionContent.jsm:1029
00:38:20.205
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 [app.js:2](moz-extension://d4e3942a-229e-4e22-914c-84cf3c9ce186/build/app.js)
    e moz-extension://d4e3942a-229e-4e22-914c-84cf3c9ce186/build/app.js:2
00:38:39.438
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
2 [index.js:4937](moz-extension://7dc32c54-ae55-472c-98b7-418dd335f71d/inject/index.js)
    sendMessage moz-extension://7dc32c54-ae55-472c-98b7-418dd335f71d/inject/index.js:4937

![forosa](https://user-images.githubusercontent.com/16869602/157558011-330ce590-c402-495a-8889-101a9f56ba5f.png)

I'm using mozilla addons such as: Dark Reader, film scores for Netflix, Netflix Watched List, PocketTube and UBlock Origin.

By looking at these loggings, I see there's something about Dark Reader, but I'm not using it on youtube.

**Comment by OsaSoft** [comment]
the search issue is related to #114  , so closing this issue to maintain just one open
