### ISSUE TITLE
Allow to only mark as watched manually

### ISSUE THREAD

**Issue by GEHORC** [OsaSoft/youtube-better-subscriptions#111]
What I want:
I wan't to mark every watched video manually by clicking the button on the video card.
Please add a checkbox to the settings that allows me to choose.

How it is right now:
Right now a video is marked as watched as soon as I click on it.
I can't seem to find a way to turn that off.

Am I crazy?
I am sure this was possible in the past.
I have "Use YouTube™'s watched gauge" unchecked.

**Comment by CameronGeisler** [comment]
I am in a similar situation. This functionality worked before, by unchecking "Use YouTube's watched gauge". However, recently, videos are being marked as watched when they're clicked on, regardless of the setting.

**Comment by OsaSoft** [comment]
Hi, is this setting what youre looking for? Should be on the extension's settings page right above the Save button
![image](https://user-images.githubusercontent.com/8895463/162632864-464ea8d8-a856-46b6-bbcf-3469312338eb.png)

**Comment by CameronGeisler** [comment]
Ah, that's what I meant. I have that setting disabled as well, but disabling doesn't fix the issue / produce the functionality that it says. I've tried refreshing, restarting computer, etc. Like GEHORC says, it used to work! And it was the reason I chose this extension over others. This issue only started happening maybe a week or two ago.

**Comment by GEHORC** [comment]
> Hi, is this setting what youre looking for? Should be on the extension's settings page right above the Save button ![image](https://user-images.githubusercontent.com/8895463/162632864-464ea8d8-a856-46b6-bbcf-3469312338eb.png)

Yes, this is what I was looking for. I was sure my eyes were tricking me, when I just didn't find it.
BUT as Cameron said this setting doesn't seem to be respected.
I just tried it again: Checked, the Setting was disabled, clicked on a video, watched two seconds, clicked on the browsers "back"- button, refreshed the subscription feed with F5. The video was now hidden.

**Comment by GEHORC** [comment]
Is there any hope of fixing this? Below are my current settings.
With both automatic options disabled, still all videos I ever start watching are immediately then marked as watched.
![2022-12-04_09h51_46](https://user-images.githubusercontent.com/81954637/205482151-5cf87165-c474-409c-8f04-51f68dcd6139.png)
