### ISSUE TITLE
Use Youtube watch gauge option ignored

### ISSUE THREAD

**Issue by NavinSangtani** [OsaSoft/youtube-better-subscriptions#115]
Hi,

I recently noticed that no matter what I set on the options page the extension will hide videos that have been marked as watched by youtube (red bar at the bottom of the thumbnail). I have this option unchecked in the options page but it seems to be ignored. Also whenever I manually set the video as unwatched by clicking on the icon on the bottom left of the thubmnail, whenever the feed gets refreshed it the video gets hidden again. 

![image](https://user-images.githubusercontent.com/62442351/167217033-14354752-fb52-4d62-b16d-f5596d588e81.png)

**Comment by SydWad** [comment]
Im having the same issue, at this point im not even sure if the extension is working at all on the home page.

**Comment by OsaSoft** [comment]
I believe this was fixed in #90 . Closing
