### ISSUE TITLE
Auto-Hide Livestreams from Subscription Feed

### ISSUE THREAD

**Issue by TakotoLuke** [OsaSoft/youtube-better-subscriptions#117]
Would there be a possibility of having a feature for automatically hiding currently airing live-streams from the subscription feed?

I find when following a ton of channels, sometimes they end up creating a really long/cumbersome list at the top of the subscription feed. No worries if not possible!

Either way, great work on this!

**Comment by grandslammer** [comment]
Related to #36 and #97

**Comment by OsaSoft** [comment]
Duplicate of #97
