### ISSUE TITLE
Thumbnail overlay UI broken on channel videos page

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#126]
Followup after #122 

Apart from breaking the hiding the of watched videos on the channel page, the YT update also broke the UI overlay added to thumbnails

**Comment by OsaSoft** [comment]
So the whole thumbnail ui and structure is shot here, the grid renderer is also completely different - however, the subs page internally uses some same parts (like the on-hover ui elements), these could be levered to rewrite something that works on both subs and channel videos pages, or separate functionality, but less tangled.
It is possible that the mark as watched button will move place/change design as necessary to get it to work

**Comment by TootY1993** [comment]
Thank you for the update

**Comment by Bolongna** [comment]
Typical of YT, got to change things just for the sake of change.  Thanks for the update and the work trying to fix their mess.

**Comment by TootY1993** [comment]
Hey @OsaSoft , any potential update on the above issue? Thank you

**Comment by OsaSoft** [comment]
So, managed to do a bit of a rough quick fix. Its not the best looking solution, but it at least works
![obrazek](https://user-images.githubusercontent.com/8895463/234380100-cc6d30a9-250e-4b6a-9edd-17c6227dbd54.png)

should roll out soon-ish
