### ISSUE TITLE
"Mark as watched"-Button no longer visible

### ISSUE THREAD

**Issue by Bapfal** [OsaSoft/youtube-better-subscriptions#133]
The button isn't showing up anymore on the subscriptions page since yesterday. The "unwatch"-Button still shows up but is now located at the video title, instead of the thumbnail.

**Comment by OsaSoft** [comment]
Yep, Youtube rolled out an update to the subs feed that breaks this... Ill try to get around to fix it asap

**Comment by OsaSoft** [comment]
Well ive investigated a bit and its not good. YT really overhauled the way the thumbnail turns into a player and shows the overlays... Not sure it can be simply rewritten to work properly.

However Ill try to at least do a "hotfix" to have a simple button somewhere around the video title, like the first few versions of the extenstion had :sweat_smile:

**Comment by Bapfal** [comment]
Aw man :(

Thanks a lot though! It's borderline impossible for me to use youtube without your extension, since I've gotten so used to it. 😅

**Comment by OsaSoft** [comment]
fyi, i also believe this will solve #126

**Comment by OsaSoft** [comment]
update: spent the entire evening on this, didnt manage to make any headway. YT is doing way too much black magic on the background. Ill try to ask some FE dev friends for a bit of help

**Comment by OsaSoft** [comment]
Good news everyone! Ive managed to do a bit of a hacky quick fix. Its not the best looking solution, but it DOES work. So fo the time being its better than nothing :)
![obrazek](https://user-images.githubusercontent.com/8895463/234379811-45d960f2-bab9-4010-80e4-4c38b79e2cc8.png)

Going out soon!

**Comment by OsaSoft** [comment]
Firefox is already approved and live, either wait for autoupdate or force extension update. Not sure how long Chrome will take, its always a bit slow

**Comment by Bapfal** [comment]
Thank you for your time and effort! =)
