### ISSUE TITLE
Hidden watched videos leave blank spots at end of rows

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#134]
Related to the YT redesign that causes #133 and #126. Each row is now its own div, so hiding elements in a row doesnt cause the other videos to "shift" over to the empty spot.

Dont know how much can be done to fix this, except for moving forward with and accelerating plans for the completely custom subs page (#30 )

**Comment by AndrewTPohlmann** [comment]
As a user, i do not mind this issue.  Easy enough to hit F5 / refresh.
