### ISSUE TITLE
Youtube changed again, can't mark as watched :(

### ISSUE THREAD

**Issue by EddyGurge** [OsaSoft/youtube-better-subscriptions#139]
Seems the latest UI update killed the 'mark as watched' button.

**Comment by Taizunz** [comment]
It's still there, it's just below the thumbnail. It uses the same UI that the frontpage has had for a while now.
It does look like there are other UI-related issues with this now as well though, so the extension probably needs a little overhaul.

**Comment by Immabed** [comment]
Indeed, other UI issues are definitely present. Hidden videos become white-space at the end of their row instead of all videos shuffling up.

A feature request I now have would be the option to resize videos to the same as the old subscription page, or even other arbitrary sizes.

**Comment by OsaSoft** [comment]
@Immabed yeah the latest YT update broke a bunch things. Already made a few issues for that like #134 . But since the way theyve changed the behaviour of the feed, its going to be pretty hard if not impossible to properly adapt to it, so creating a new custom feed might be the only way in the end

**Comment by Bolongna** [comment]
The latest changes just make it even worse to use, but hey it "changed". Really wish they would just leave it alone. The large sizes and other BS are just annoying.

**Comment by bonbonboi** [comment]
I'm waiting for a quick patch!

**Comment by bonbonboi** [comment]
> 

nothing is there!

**Comment by Bolongna** [comment]
Strange, on mine it is below the video.
![image](https://github.com/OsaSoft/youtube-better-subscriptions/assets/85271732/a9e579fd-0fe1-4386-8d8f-09d36119673b)

**Comment by OsaSoft** [comment]
@bonbonboi can you check if you have the latest version (0.17.3) and post a screenshot of the subs feed?

**Comment by bonbonboi** [comment]
> @bonbonboi can you check if you have the latest version (0.17.3) and post a screenshot of the subs feed?

Thanks for reminding me about that, actually I found out that it's 0.17.1 and that lead me to another thing to investigate  with my chrome, which is it does not update extensions automatically, I checked on the extensions, some of them are outdated as well. Later I'll investigate the cause of that issue, but for now I have uninstalled and reinstalled your extension to get the latest version which is 0.17.3 and yeah the eye icon back in that place near the views counter as in Bolongna screenshot,

**Comment by borbra** [comment]
I also had version 0.17.3, updated to 0.17.4 and it's working again :D
Thank you @OsaSoft for making such a good extension, it's a pain to use youtube without it.
