### ISSUE TITLE
Hide short broke suscriptión page

### ISSUE THREAD

**Issue by cansi22** [OsaSoft/youtube-better-subscriptions#140]
When I activate "Hide Shorts automatically" the subscription page appears with gaps and the videos are not repositioned.
About 2 weeks ago it worked without problems.

[Image Example](https://i.imgur.com/xlOjBTm.png)

**Comment by OsaSoft** [comment]
A new version has been released (v0.17.5) that has probably fixed this issue.
Can you check if this is still happening?

**Comment by cansi22** [comment]
Works 100% 😊
