### ISSUE TITLE
Watched Status Changes with Row Width?

### ISSUE THREAD

**Issue by znxster** [OsaSoft/youtube-better-subscriptions#141]
Videos can appear watched/unwatched depending on how many items are in the row.

For instance, if we use a basic (watched) versus [unwatched]

1 video per row (2 is incorrect)
- (1)
- [2] - incorrect
- [3]
- [4]

2 video per row (3 is incorrect)
- (1) (2)
- (3) [4]

Using 3 or 4 per row seems to correctly line up.

I would guess that this on/off nature has something to do with the new "row" formatting that YT has done to their design.

I have also seen the watched ("eye") button disappear on scroll, which might play into the above, as it can occur when resizing the width.

**Comment by OsaSoft** [comment]
A new version has been released (v0.17.5) that has probably fixed this issue.
Can you check if this is still happening?

**Comment by znxster** [comment]
@OsaSoft I can confirm the latest update has resolved both the incorrect watched status and the disappearing eye. Great stuff thanks!
