### ISSUE TITLE
Not hiding shorts

### ISSUE THREAD

**Issue by al52025** [OsaSoft/youtube-better-subscriptions#145]
I guess YouTube changed their layout again because the hide shorts option isn't hiding them anymore on my subscriptions page

**Comment by ZeebaEata** [comment]
Yes, YouTube has added a new abominable Shorts panel in Subscriptions instead of infesting the feed with individual Shorts.  Help us OsaSoft, you are our only hope!

**Comment by NossieUK** [comment]
it's a sad sad state of affairs when we need third parties to keep sites like youtube usable. :(

**Comment by Zipster79** [comment]
If you are looking for a temporary solution then you can use uBlock Origin as explained in this video, I have just tried and it works a treat on desktop, shorts are gone and the watched video gaps go as well with the exception of the opening line.

https://www.youtube.com/watch?v=HyWxtnOWx4E

**Comment by ZeebaEata** [comment]
Thank you [Zipster79](https://github.com/Zipster79), works like a charm!

**Comment by GEHORC** [comment]
> If you are looking for a temporary solution then you can use uBlock Origin as explained in this video, I have just tried and it works a treat on desktop, shorts are gone and the watched video gaps go as well with the exception of the opening line.
> 
> https://www.youtube.com/watch?v=HyWxtnOWx4E

This is really cool, thank you. I made some observations:
- It also works with AdNauseam.
- Only the 10th OR 11th line of your shared filter list is needed to hide the shorts-shelf in the subscription box.
- The last (19th) line does something cool as well.
You know how better subscriptions doesn't reorder the grid of videos? If you hide all but one video in a row, this row will show only one video. The last line of this filter list will reorder the grid so videos will move upward to fill empty spots in the grid.

**Comment by OsaSoft** [comment]
@GEHORC 
> The last (19th) line does something cool as well.
You know how better subscriptions doesn't reorder the grid of videos? If you hide all but one video in a row, this row will show only one video. The last line of this filter list will reorder the grid so videos will move upward to fill empty spots in the grid.


ooooh! Thats a very interesting observation... Ill have to take a look to see if I can use that as its incredibly annoying :D

**Comment by OsaSoft** [comment]
A new version has been released (v0.17.5) that has probably fixed this issue.
Can you check if this is still happening?

**Comment by GEHORC** [comment]
> A new version has been released (v0.17.5) that has probably fixed this issue.
> Can you check if this is still happening?

Yes, was already pleasantly surprised, since it wasn’t mentioned in the patchnotes. Currently I have all the ublock rules deactivated and the short shelf is still gone.
