### ISSUE TITLE
YT changed again? I am seeing all my watched vids

### ISSUE THREAD

**Issue by gregkopp** [OsaSoft/youtube-better-subscriptions#147]
I am seeing all my watched vids with the red bar, and there's no longer a "mark watched" eye-con.

**Comment by GEHORC** [comment]
Same here...

**Comment by SSJ3Goku** [comment]
Same.

**Comment by OsaSoft** [comment]
Oh great... Seems like youtube is rolling out yet another update i guess...
Those affected, can you send a screenshot and the source of the page? I can
try to figure out if theres a simple way for me to fix it without actually
having the new version myself 😅

**Comment by Urhas** [comment]
Same issue here. What's the best way to send the source over?

Errors :
[YT-Better-Subs] ERROR!  Cannot read properties of undefined (reading 'remove')

TypeError: Cannot read properties of undefined (reading 'remove')
    at buildMarkWatchedButton (subs-ui.js:152:34)
    at SubscriptionVideo.addButton (SubscriptionsVideo.js:15:26)
    at removeWatchedAndAddButton (subs-ui.js:242:17)
    at subs.js:118:21

**Comment by gregkopp** [comment]
￼

**Comment by gregkopp** [comment]
[YouTube.zip](https://github.com/OsaSoft/youtube-better-subscriptions/files/12469440/YouTube.zip)

Screen shot and source code attached

**Comment by SSJ3Goku** [comment]
[Here is a screenshot of my feed and the source code.](https://github.com/OsaSoft/youtube-better-subscriptions/files/12469590/better.sub.feed.error.zip)

**Comment by Bolongna** [comment]
Same here, Both on Edge and Chrome. There is a hide item in the 3 dot menu and it did hide one video after I watched it but it acts like it ignores better subs after that.

**Comment by gregkopp** [comment]
Seems like if the first videos in my subscription feed have been watched, they are hidden. But once it gets to an unwatched video, every video after that, watched or unwatched, is shown in my feed. Although even that seems a bit intermittent.

**Comment by niai** [comment]
Been using this pull request for a few hours now and not seeing any issues. Thanks @ericfrazer

**Comment by gregkopp** [comment]
Trying it myself. Looks good so far.

**Comment by SSJ3Goku** [comment]
Ok so how do I fix this myself? I dunno what a pull request is, haven't done anything with code before.

**Comment by OsaSoft** [comment]
Thanks @ericfrazer ! Rolling out the update asap

**Comment by OsaSoft** [comment]
Firefox has been approved. You can either wait for the browser to automatically update, or you can get the new version quicker by typing about:addons into the url address, then the little settings wheel on the top right and "Check for Updates".

Chrome has still not been approved

**Comment by OsaSoft** [comment]
Actually, chrome has just been approved as well :)

**Comment by SSJ3Goku** [comment]
Hooray chrome is fixed!

**Comment by isgdre** [comment]
Thanks for the quick turn around.  
It's shocking to me how bad YouTube's standard interface is.

**Comment by Bolongna** [comment]
Thanks for the quick patch. I did notice that if I hide a video using yts own hide that on refresh there are no blank spaces. Is there any way that could be used in YT better subs? Like maybe the watched button could also hit the hide toggle? Don't do any modern coding so not sure if that's a possible thing. That might cure the empty spaces.
