### ISSUE TITLE
Watched button failing to appear

### ISSUE THREAD

**Issue by AndrewTPohlmann** [OsaSoft/youtube-better-subscriptions#148]
This is 0.17.3 version + Chrome 116.0.5845.141 (updated as of this post) in a Windows 10 environment.

![Capture](https://github.com/OsaSoft/youtube-better-subscriptions/assets/4632846/80764abd-8e2b-4e32-bea0-575316dac451)

Pretty sure recent.

**Comment by OsaSoft** [comment]
Seems i just got the update as well. Ill investigate asap

**Comment by SSJ3Goku** [comment]
I got the same thing as well.

**Comment by ericfrazer** [comment]
duplicate of issue #147 . PR #149 resolves this one

**Comment by OsaSoft** [comment]
closing as duplicate of #147
