### ISSUE TITLE
Watched overlay for videos marked watched by user

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#18]
When a video is marked using the Mark as watched button and watched are not hidden, add an overlay to the thumbnail to make it clear it is marked as watched

**Comment by macearl** [comment]
I think it could also be useful to insert a "marked as unwatched" button where the mark as watched button was. Just so it is possible to undo accidental clicks

**Comment by OsaSoft** [comment]
Yeah, mark as unwatched is already on the todo list, see issue #19

**Comment by macearl** [comment]
Oh seems like I overlooked that one.

Just keep up the good work then I guess ;)
