### ISSUE TITLE
[Bug] Small Thumbnails and no text boxes make this extension unusable

### ISSUE THREAD

**Issue by nSkade** [OsaSoft/youtube-better-subscriptions#187]
As of today or yesterday, thumbnails appear very small and there is no text anymore, this seems to be coming from an Youtube update

![grafik](https://github.com/user-attachments/assets/82b8beee-0ed4-4297-a3c7-9391df6d124c)

tried disabling other extensions, but disabling better subscriptions fixed the issue.
It might be something todo with how youtube loads videos containers into the sub box as they are the same size:
(maybe they are firstly loaded small and then resized and filled with content

![grafik](https://github.com/user-attachments/assets/9af1538c-d571-4bd0-a960-ee551276e852)

I would be very grateful if this Issue gets resolved. :)

**Comment by nSkade** [comment]
I am using Firefox btw.

**Comment by LEMental** [comment]
Happening to me as well.

**Comment by nSkade** [comment]
chrome seems to have the same problem, tested it now

**Comment by vespertinee** [comment]
same issue here

**Comment by Tzalim** [comment]
The same issue is here on the latest Vivaldi on Garuda (Arch) Linux.

**Comment by mocanew** [comment]
I'd like to fix this issue, but on any of my browsers and accounts I still get the old (working) layout.

**Comment by allanmckenzie** [comment]
Hi @mocanew Thanks for this extension. For me this extension is vital and without it youtube is unbearable. I have the same issue - both with Chrome and with Brave. I'm using a Mac. I'm not sure if that makes a difference.

I'm really hoping you can fix this. I've disabled the extension for now and youtube is bugging the hell out of me

**Comment by nSkade** [comment]
> I'd like to fix this issue, but on any of my browsers and accounts I still get the old (working) layout.

First I wanted to suggest using a vpn, but this seems to be bound to youtube accounts, logging out restored the working layout with the plugin working. I tried clearing cookies/cache but that does nothing.

**Comment by nSkade** [comment]
It looks like that the problem is that the a child div of the grid does chooses the last div container for the width when no style width is specified. I created this userscript to set it to 700% (might need other value) and it works well:

```// ==UserScript==
// @name       yt better subscription small grid fix
// @namespace   https://tampermonkey.net/
// @version     0.1
// @description whi utube change all the tiem?
// @author       nSkade
// @match           https://www.youtube.com/*
// @match           https://www.youtube-nocookie.com/*
// @match           https://m.youtube.com/*
// @match           https://music.youtube.com/*
// @grant       none
// ==/UserScript==

(function() {
'use strict';

console.log('Hello yt better subscription small grid fix');

const observer = new MutationObserver(mutationsList => {

const targetDiv = document.querySelector('.ytd-two-column-browse-results-renderer.style-scope');
if (targetDiv) {
  console.log('Found targetDiv:', targetDiv);

  mutationsList.forEach(mutation => {
    if (mutation.type === 'childList') {
      console.log('Mutation detected:', mutation);
      // Re-apply width adjustment on mutation
      const videoItems = targetDiv.querySelectorAll('ytd-rich-item-renderer.style-scope');
      videoItems.forEach(item => {
        const innerDiv = item.querySelector('div:nth-child(1)');
        if (innerDiv) {
          innerDiv.style.width = '700%';
        }
      });
    }
  });

}
});

observer.observe(document, { childList: true, subtree: true });

})();
```

I am a noob in that regard, this script seems inefficient because values get set everytime something in the document changes. Id appreciate improvement suggestions.

**Comment by ErikMartensson** [comment]
@nSkade I tried to improve your solution a little bit. This seems to work fine for me.

It's still a hack and I'm patiently waiting for an official update.

```userscript
// ==UserScript==
// @name       yt better subscription small grid fix
// @namespace   https://tampermonkey.net/
// @version     0.2
// @description whi utube change all the tiem?
// @author       nSkade and friends
// @match           https://www.youtube.com/*
// @match           https://www.youtube-nocookie.com/*
// @match           https://m.youtube.com/*
// @match           https://music.youtube.com/*
// @grant GM_addStyle
// ==/UserScript==

GM_addStyle('ytd-rich-item-renderer[rendered-from-rich-grid] { width: auto !important; }');
```

**Comment by MisterTickle** [comment]
@nSkade  and @ErikMartensson , thank you both very much! 
I've only today seen this problem - I think youtube is changing its views gradually over a longer period.

**Comment by gregkopp** [comment]
Same issue for me here in Chrome.

**Comment by vespertinee** [comment]
> @nSkade I tried to improve your solution a little bit. This seems to work fine for me.
> 
> It's still a hack and I'm patiently waiting for an official update.
> 
> ```
> // ==UserScript==
> // @name       yt better subscription small grid fix
> // @namespace   https://tampermonkey.net/
> // @version     0.2
> // @description whi utube change all the tiem?
> // @author       nSkade and friends
> // @match           https://www.youtube.com/*
> // @match           https://www.youtube-nocookie.com/*
> // @match           https://m.youtube.com/*
> // @match           https://music.youtube.com/*
> // @grant GM_addStyle
> // ==/UserScript==
> 
> GM_addStyle('ytd-rich-item-renderer[rendered-from-rich-grid] { width: auto !important; }');
> ```

hey does your fix work? could you walk me thru the process of implementing it on my browser?

**Comment by MisterTickle** [comment]
> > @nSkade I tried to improve your solution a little bit. This seems to work fine for me.
> > It's still a hack and I'm patiently waiting for an official update.
> > ```
> > // ==UserScript==
> > // @name       yt better subscription small grid fix
> > // @namespace   https://tampermonkey.net/
> > // @version     0.2
> > // @description whi utube change all the tiem?
> > // @author       nSkade and friends
> > // @match           https://www.youtube.com/*
> > // @match           https://www.youtube-nocookie.com/*
> > // @match           https://m.youtube.com/*
> > // @match           https://music.youtube.com/*
> > // @grant GM_addStyle
> > // ==/UserScript==
> > 
> > GM_addStyle('ytd-rich-item-renderer[rendered-from-rich-grid] { width: auto !important; }');
> > ```
> 
> hey does your fix work? could you walk me thru the process of implementing it on my browser?

Install an extension called "Tampermonkey" 
Then add it in there as a user script.
Paste it into the editor window, and save. That should be it!

**Comment by vespertinee** [comment]
> > > @nSkade I tried to improve your solution a little bit. This seems to work fine for me.
> > > It's still a hack and I'm patiently waiting for an official update.
> > > ```
> > > // ==UserScript==
> > > // @name       yt better subscription small grid fix
> > > // @namespace   https://tampermonkey.net/
> > > // @version     0.2
> > > // @description whi utube change all the tiem?
> > > // @author       nSkade and friends
> > > // @match           https://www.youtube.com/*
> > > // @match           https://www.youtube-nocookie.com/*
> > > // @match           https://m.youtube.com/*
> > > // @match           https://music.youtube.com/*
> > > // @grant GM_addStyle
> > > // ==/UserScript==
> > > 
> > > GM_addStyle('ytd-rich-item-renderer[rendered-from-rich-grid] { width: auto !important; }');
> > > ```
> > 
> > 
> > hey does your fix work? could you walk me thru the process of implementing it on my browser?
> 
> Install an extension called "Tampermonkey" (clue near the top of the script ;) ) Then add it in there as a user script. Paste it into the editor window, and save. That should be it! HTH

wonderful, i have tampermonkey but never used a user script before.

it works great, thanks

**Comment by GarrettRobinson** [comment]
Got the issue today as well, presumably a YT layout change. Can confirm the flex grid width fix works. Thanks @nSkade 

Implemented mine in the native userContent.css for Firefox with this snippet
Note: requires opening a new tab after saving userContent.css

`@-moz-document url-prefix(https://www.youtube.com) {
    ytd-rich-item-renderer[rendered-from-rich-grid] {
        width: auto !important;
    }
}`

**Comment by d4kir92** [comment]
hopefully this get a fix

**Comment by GarrettRobinson** [comment]
Narrowed the issue down to [line 93 in subs.css](https://github.com/OsaSoft/youtube-better-subscriptions/blob/20ed9844647ff1ae4dfcadc2a9c9ff877a5618ce/subs.css#L93) which changes the YT `contents` div from `display: flex` to `display:grid`.

 Seems to break downstream width calculations for `--ytd-rich-item-row-usable-width` on `ytd-rich-item-renderer[rendered-from-rich-grid]`

`--ytd-rich-item-row-usable-width: calc(100% - var(--ytd-rich-grid-gutter-margin)*2);`
I believe this `100%` reference to the parent container (the `contents` div) is behaving differently when it's a `display: grid`

**Comment by FranciscoFB7** [comment]
Same can't use it on chrome

**Comment by zf1z** [comment]
Here is a bookmarklet that should work (change width and height if needed)

javascript:(function() {
    var elements = document.querySelectorAll('.style-scope.ytd-rich-item-renderer');
    elements.forEach(function(element) {
        element.style.width = '358.656px';
        element.style.height = '323.734px';
    });
})();

**Comment by mocanew** [comment]
@OsaSoft could you have a look and if everything is fine do a merge of #189 and extension update?

**Comment by d4kir92** [comment]
seems like its abandoned extension, sad :(
any alternatives for that?

**Comment by MisterTickle** [comment]
> seems like its abandoned extension, sad :( any alternatives for that?

I don't think it's abandoned at all. It's way too soon to leap to that conclusion IMHO.

**Comment by d4kir92** [comment]
> > seems like its abandoned extension, sad :( any alternatives for that?
> 
> I don't think it's abandoned at all. It's way too soon to leap to that conclusion IMHO.

ok i trust you :P

**Comment by TootY1993** [comment]
> > seems like its abandoned extension, sad :( any alternatives for that?
> 
> I don't think it's abandoned at all. It's way too soon to leap to that conclusion IMHO.

I wish I were that confident, I'm seeing a lot of issues reported but no response from the creator. Hopefully, it's still active but would be great if someone had an alternative, I wasn't able to find.

**Comment by d4kir92** [comment]
if i had time i would make my own extension for that..

**Comment by OsaSoft** [comment]
Hey all, i am so sorry for the long delay in any sort of reply. I've been so busy I haven't even been using YouTube to notice the issue. I am amazed at the outpouring of support and love for this little extension from you all :sweat_smile: 

Ill take a look at the related PRs and try to release the update asap

**Comment by MisterTickle** [comment]
> Hey all, i am so sorry for the long delay in any sort of reply. I've been so busy I haven't even been using YouTube to notice the issue. I am amazed at the outpouring of support and love for this little extension from you all 😅
> 
> Ill take a look at the related PRs and try to release the update asap

Yay! Thanks.
I do love it, YouTube's subscription page is utterly unusable without it :)

**Comment by d4kir92** [comment]
> Hey all, i am so sorry for the long delay in any sort of reply. I've been so busy I haven't even been using YouTube to notice the issue. I am amazed at the outpouring of support and love for this little extension from you all 😅
> 
> Ill take a look at the related PRs and try to release the update asap

NICE THX!!!

**Comment by OsaSoft** [comment]
> > Hey all, i am so sorry for the long delay in any sort of reply. I've been so busy I haven't even been using YouTube to notice the issue. I am amazed at the outpouring of support and love for this little extension from you all 😅
> > Ill take a look at the related PRs and try to release the update asap
> 
> NICE THX!!!

Thank @mocanew who actually found the issue and fixed it 😅 I just merged and published it to mozilla and chrome, and even just doing that took me way too long... Im really sorry

**Comment by d4kir92** [comment]
thx all then :D
i am just happy that it works soon :D

**Comment by OsaSoft** [comment]
Firefox was approved immediately, so either your browser will pull it soon
or you can force an update in the addons tab. Chrome 🤷‍♂️ you never know
how long it will take 😅

**Comment by d4kir92** [comment]
yes chrome webstore is slow

**Comment by MisterTickle** [comment]
I now have the new version from the Chrome shop. Many thanks!
(btw, for those using the Tampermonkey script, you have to turn that off, otherwise it interferes with the fix!)
