### ISSUE TITLE
Not working (Firefox and Chrome)

### ISSUE THREAD

**Issue by ApollonPrim** [OsaSoft/youtube-better-subscriptions#26]
Thank you for your extension! It is the only addon with such functionality.
I am interesting in hiding videos forever both at subscriber page and channels and search page.

But extension doesn't work on Firefox (58.0.2 x64) and Chrome (64). There is no any buttons at YouTube and settings.
Need help. Thanks.

**Comment by ApollonPrim** [comment]
It becomes work after refreshing page for some times. At subscribers page and recommended at main page. But can stop work after refreshing again.

Hope it's possible to extend functionality to channels and search page. Thanks.

**Comment by OsaSoft** [comment]
Yeah, recently was pointed to this bug. Its already discussed in Issue #25 .

As far as hiding on channel pages, its not planned at the moment, but its a possible feature for a future version, ill keep it in mind.

Thanks for the feedback!
