### ISSUE TITLE
Collapsible subscription groups

### ISSUE THREAD

**Issue by Tyuyf** [OsaSoft/youtube-better-subscriptions#31]
Was wondering if you had any plans to add collapsible subscription groups, similar to Mattie342's Chrome extension ' YouTweak for Youtube'. I loved being able to collapse a section instead of having to scroll through it.
(https://github.com/Mattie432/YouTweak)

![collapsible sub groups](https://user-images.githubusercontent.com/39038638/39681298-43542162-5177-11e8-8ce9-486fff3e23b0.png)

**Comment by OsaSoft** [comment]
Hi and thanks for your suggestion. Its definitely an interesting feature and I probably will implement it sooner or later! 
However, Im not sure if it should be in this addon, or make a new one for it.

Ill definitely put this on a TODO list, though Im not sure when Ill be able to get around to working on it.

**Comment by Tyuyf** [comment]
Probably should have thought about this earlier, but [here's](https://github.com/Mattie432/YouTweak/blob/master/src/chrome/ContentScripts/f_CollapseSubscriptionVideos.js) the link to the code that the other extensions uses.

**Comment by OsaSoft** [comment]
Alright, this feature should start rolling out soon in version 0.10 :smile_cat:
