### ISSUE TITLE
Sometimes the checkbox won't appear

### ISSUE THREAD

**Issue by LupinIII** [OsaSoft/youtube-better-subscriptions#32]
Sometimes the checkbox to hide watched videos does not appear and the page has to be reloaded. It seems to happen mostly (but not consistently) the first time when opening youtube after browser launch.

I have made a fork/branch where I changed the way the checkbox is added:
[https://github.com/LupinIII/youtube-better-subscriptions/tree/more-reliable-checkbox-add](url)
With that I never had the problem of the checkbox not appearing.

(I have made a few other branches where I fix something I had a problem with, or check the master branch in my fork where I combined all of it)

**Comment by OsaSoft** [comment]
Hey,
please check if #40 has resolved this, or if your fix is still relevant. Version 0.7 containing these changes should start rolling out fairly soon

Thanks :)

**Comment by OsaSoft** [comment]
Hey @LupinIII , any update on whether the recent updates have fixed this so we can either close or move forward with this issue?

**Comment by LupinIII** [comment]
I didn't have much time to try it out, but up to now it did not happen again yet with the 0.7 version.

**Comment by OsaSoft** [comment]
Alright, thanks for the info. I believe this should be fixed with the new udpates, so I'm closing this issue. If the issue resurfaces, please let me know
