### ISSUE TITLE
Make multi-browser

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#4]
@SamHH said:
> There's no need for it to be Firefox-exclusive. Develop against the WebExtension pseudo-standard and you'll have Chrome (+ others) support alongside Firefox with virtually no extra code.

**Comment by SamHH** [comment]
Here are the docs you can refer to: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

You can also check out this as my most recent multi-browser webext: https://github.com/SamHH/bukubrow/tree/master/webextension/src
