### ISSUE TITLE
I've magically resubbed to channels I unsubbed from months ago!

### ISSUE THREAD

**Issue by grandslammer** [OsaSoft/youtube-better-subscriptions#42]
Hey I'm not sure if this issue is to do with the extension but I'll post it anyway seeing that there have been a few updates pushed today.

I've noticed in the last couple of hours that my channel has magically resubscribed to at least 3 channels I unsubbed from months ago, and their videos are showing up on my subscriptions page! When I view a video from one of the channel, the Subscribe button is displaying as if I have subscribed to them (ie it's grey and says Subscribed as opposed to red).

This is a very weird issue! And it's highly likely that it's an issue with YouTube itself and not the extension. It's a coincidence seeing as there were a few updates to the extension pushed today.

Is anybody else experiencing the same behaviour?

**Comment by OsaSoft** [comment]
Seems theres no further news about this, Closing the issue
