### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by OsaSoft** [OsaSoft/youtube-better-subscriptions#44]
Screenshots on both Chrome and Mozilla are very old and need to be updated

**Comment by prediscover** [comment]
![image](https://user-images.githubusercontent.com/10902462/52670964-bd904480-2ece-11e9-9279-3b55b23d757a.png)
![image](https://user-images.githubusercontent.com/10902462/52671012-d993e600-2ece-11e9-894e-92323c063cac.png)
![image](https://user-images.githubusercontent.com/10902462/52671042-eb758900-2ece-11e9-884c-3de84b0ef4bc.png)

Here's a few. idk if this is what you meant by the help wanted tag

**Comment by OsaSoft** [comment]
Hey @prediscover , yes thats exactly what I meant :) thanks a lot! Ill add your screenshot to the extension pages in firefox and chrome

Could I ask you for one more screenshot, where the **Hide Watched** is unchecked, ie hidden videos are showing?

**Comment by prediscover** [comment]
![image](https://user-images.githubusercontent.com/10902462/52977639-d55e4180-3382-11e9-84c6-af91a22a1374.png)

**Comment by prediscover** [comment]
![image](https://user-images.githubusercontent.com/10902462/52977664-e909a800-3382-11e9-8b17-9017a73e8e57.png)

**Comment by prediscover** [comment]
Here you go!
![image](https://user-images.githubusercontent.com/10902462/52977686-076fa380-3383-11e9-84d9-9c9d51d17905.png)

**Comment by OsaSoft** [comment]
Thats awesome. Thanks a lot!
