### ISSUE TITLE
The older videos never load if all newer videos are viewed

### ISSUE THREAD

**Issue by DavidDrezen** [OsaSoft/youtube-better-subscriptions#45]
When the checkbox "hide all videos" is checked and all newer videos are viewed (so there is no scrollbar), the older videos never loads. Adding manually a scrollbar (for example with a simple css `min-height: 101vh;`) seems to fix the problem.

**Comment by OsaSoft** [comment]
Hey,
hmm thats weird. There is functionality in place that launches the "load more" procedure on YT when all videos are hidden in the new Polymer layout, and Ive tested Mark all as watched in old layout to see  that it loads automatically.

Could you please provide some more info on your setup? (screenshots, if there are any errors in console log, etc)

Thanks

**Comment by DavidDrezen** [comment]
I have this problem again, there is no error in the console : 

![capture](https://user-images.githubusercontent.com/1626386/44629478-58f92180-a950-11e8-9544-2dcdfb7d9638.JPG)

It's really strange, I've not any clue on why it appens...

**Comment by OsaSoft** [comment]
Ah, I think I know whats happening thanks to the screenshot. Seems like an edge case I didnt account for.
Thanks for the info, Ill take a look at it hopefully soon

**Comment by DavidDrezen** [comment]
Perfect, if you need more informations just ask me !

**Comment by ZeebaEata** [comment]
I had this issue too and have investigated it (from the user side). Seems like the loading stops after all the videos that have been initially present on screen are hidden. 

**To force further loading of the videos, you can scroll the left sidebar.** Sometimes mere hovering the mouse over the sidebar initiated further loading.

**Comment by OsaSoft** [comment]
Im almost sure its because the way the load more videos is triggeres atm is only performed when there are NO visible videos. So if there is one or two vids that arent hidden, it doesnt get triggered

**Comment by OsaSoft** [comment]
@ZeebaEata thanks for that info! I was able to use that to do a nice workaround to forcing YT to load more videos. The fix for this will be rolling out soon in version 0.8.1

**Comment by ZeebaEata** [comment]
OsaSoft, glad to be of help! Thank YOU for the most useful add-on!
