### ISSUE TITLE
Hide only fully watched videos

### ISSUE THREAD

**Issue by DavidDrezen** [OsaSoft/youtube-better-subscriptions#46]
Videos not fully watched are hidden, it would be more accurate to only hide the videos totally watched.

**Comment by OsaSoft** [comment]
This is working as intended, as often the way youtube marks watch completion is inaccurate and many people dont watch videos until the very very end.
Not to mention, YTs watch mark might not be used in future versions at all.
Maybe in the future this could be configurable, but definitely not anytime soon, sorry.
Thanks for the feedback though

**Comment by phoenixoflight** [comment]
I would also like to see this as a configurable option in the future.
