### ISSUE TITLE
Not activing when going direct (Reverse of #25?)

### ISSUE THREAD

**Issue by znxster** [OsaSoft/youtube-better-subscriptions#56]
Hey, I am using the latest Firefox (66.0.3 (64-bit) with the newest version of better subscriptions available from the AddOns site (v0.10 Apr 29, 2019).

This issue seems to be the reverse of #25.

If I go to the top level site (www.youtube.com) and then click on subscriptions, everything works fine. However if I go directly to https://www.youtube.com/feed/subscriptions/ it doesn't enable.

**Comment by znxster** [comment]
I have just noticed and I think it is just the trialing /.
- https://www.youtube.com/feed/subscriptions = working
- https://www.youtube.com/feed/subscriptions/ = not working

**Comment by OsaSoft** [comment]
Hey, thanks for letting me know.
It seems it might be caused by the trailing /, which might be an issue on more pages. Ill have a look and get a fix out (hopefully) soon

**Comment by OsaSoft** [comment]
Ive fixed this in 052688b in version 0.11. I've just released the new version and it should be rolling out on Firefox and Chrome soon
