### ISSUE TITLE
Feature: Hide watched videos on channels

### ISSUE THREAD

**Issue by phoenixoflight** [OsaSoft/youtube-better-subscriptions#59]
Sometimes I find that I don't subscribe to a channel but instead just visit directly because they put out more content then I care to see in my subscriptions page.  I would love to see this extension extended to filter out watched videos directly on channel pages.

For example:
https://www.youtube.com/user/Northernlion/videos

Thanks!

**Comment by ZeebaEata** [comment]
Yes, that would be a very handy addition. Without it, watching old content on channels with lots of short videos, like SciShow, is a torture.

**Comment by OsaSoft** [comment]
duplicate of #37 

to be resolved in #83
