### ISSUE TITLE
Extension does not mark strreams as watched

### ISSUE THREAD

**Issue by grandslammer** [OsaSoft/youtube-better-subscriptions#6]
The extension does not mark live streams as watched. This included completed streams, nad also scheduled streams. I would like completed streams to be hidden, and to keep scheduled streams in my subscription list (maybe with an option to hide scheduled streams).
![screenshot_3](https://user-images.githubusercontent.com/18541062/32866271-cb8cdbd2-ca5e-11e7-881a-53496907a9c0.png)

**Comment by OsaSoft** [comment]
Thanks for letting me know! Since I dont watch streams on YouTube, completely missed that this wasnt working. Ill take a look at it

**Comment by OsaSoft** [comment]
hey @grandslammer, this should have been resolved in e95bd33e78a722f818263586ce253d6ac0d7ae83 . Can you please confirm whether that is the case? I havent been able to catch any streams while they were live, so couldnt confirm myself.

**Comment by grandslammer** [comment]
I can confirm it's working. Thanks.
