### ISSUE TITLE
"Mark watched" not working?

### ISSUE THREAD

**Issue by surfarcher** [OsaSoft/youtube-better-subscriptions#65]
Videos I mark as watch in my sub list aren't being hidden when I return to the subscription page. I've tried "clear watched videos" in options and re-marking them with no luck.

**Comment by surfarcher** [comment]
I can see many of these videos are marked "watched". They just aren't being hidden.

**Comment by OsaSoft** [comment]
Hi, could it be you have the "Hide watched" toggle switched to "off"?

**Comment by surfarcher** [comment]
Nah. I've tried toggling that multiple times. Most watched videos get hidden but there are a persistent few that don't.

**Comment by OsaSoft** [comment]
hmm that seems pretty weird. Can you please attach some screenshots?
Also if you could go to the settings page and check "Enable logging", then
after opening the Developer Console in your browser refresh the subs page
and send the logs you get there as well

pá 1. 11. 2019 v 17:53 odesílatel surfarcher <notifications@github.com>
napsal:

**Comment by surfarcher** [comment]
OK I've provided 2 examples. 
Example 1 shows a video that's been watched but is still appearing.
Example 2 shows another video I've watched that's still appearing. But I then hit the eye to hide it and it comes back! Note between 2-3 and 2-4 I have to mark all the videos I know I've watched.
![1-2 Subscriptions example](https://user-images.githubusercontent.com/2238575/68632667-39431e80-053f-11ea-885b-b83144d32014.JPG)
![2-1 Subscriptions example](https://user-images.githubusercontent.com/2238575/68632668-39431e80-053f-11ea-873d-793f6df1aa6f.JPG)
![2-2 Subscirptions marked watched](https://user-images.githubusercontent.com/2238575/68632669-39431e80-053f-11ea-91aa-6d04f18708c0.JPG)
![2-3 History watched](https://user-images.githubusercontent.com/2238575/68632670-39dbb500-053f-11ea-8307-79110704cb96.JPG)
![2-4 Subscriptions back again](https://user-images.githubusercontent.com/2238575/68632671-39dbb500-053f-11ea-8905-59a92ec641c3.JPG)
![1-1 Watched example](https://user-images.githubusercontent.com/2238575/68632674-3a744b80-053f-11ea-8a1d-20503f1a6a9c.jpg)

**Comment by surfarcher** [comment]
Zipped dev console log file...
[www.youtube.com-1573520037233.log.zip](https://github.com/OsaSoft/youtube-better-subscriptions/files/3833825/www.youtube.com-1573520037233.log.zip)

**Comment by OsaSoft** [comment]
Thanks. Ive been away on holidays and without a computer for a while, but now Im back. Ill take a look at it as soon as I get a chance

**Comment by surfarcher** [comment]
No problems at all OsaSoft - no pressure at all mate.

And BTW I greatly appreciate all that you do for the community with this plugin!

**Comment by surfarcher** [comment]
My new suggestion under issue #78 could completely remediate this bug report.

**Comment by OsaSoft** [comment]
Hey, are you still having this issue? Sorry for the inactivity :/

**Comment by surfarcher** [comment]
Real life get sin the way, I understand that.

As of a few weeks ago I was. I will retest but that might take a few days. I'll report back as soon as I've formally verified.

**Comment by surfarcher** [comment]
I can confirm that this is still happening today.

On reflection I can say this happens consistently to videos from the same channels. Most channels are unaffected, but once it starts happening to videos from a given channel it starts happening consistently to all the videos from that channel. Another thing I have noticed is that the affected videos generally don't have any red bar (partially or completely watched) in the subscription page.

**Comment by MarcLaf** [comment]
I seem to be having this issue (or similar). If I manually toggle hide using the eye icon (for videos I don't want to watch), if I refresh or go back to subscription page they return. Does the manual toggle only work for the current viewing of the page?
