### ISSUE TITLE
Settings page not loading correctly

### ISSUE THREAD

**Issue by Alfie94** [OsaSoft/youtube-better-subscriptions#79]
Better Subscriptions for YouTube version: 0.13.1.1
Chrome version: Version 81.0.4044.122 (Official Build) (64-bit)

I'm trying to view the settings menu, but it doesn't load correctly. I think it used to work, but have no idea what I've changed on my system to have it stop. I've attached an image to show how it looks.

Also, it used to remember if I had the "Hide watched videos" active, but now I have to toggle to hide every time I load the subscriptions page.

![chrome_ISfRooahGk](https://user-images.githubusercontent.com/6684330/79930047-5d385380-843f-11ea-8fd8-da5104430bca.png)

**Comment by WoLpH** [comment]
You can refresh the page as a workaround :)

**Comment by OsaSoft** [comment]
havent stumbled upon this issue since. Closing
