### ISSUE TITLE
[FEATURE REQUEST] Load on YouTube Home Page

### ISSUE THREAD

**Issue by meechgalhuquot** [OsaSoft/youtube-better-subscriptions#80]
I still force YouTube to use the classic layout because I hate the new design. This tweak still works fine on the subscriptions tab on the classic layout and it used to work just fine when I went to the homepage as well as long as I did not refresh. Today YouTube broke functionality that  used the cookies to determine whether to use the new or old layout, and now "?disable_polymer=1" has to be added to the end of the URL to use the old layout. The problem with this is that YouTube forces a refresh and the new GreasyFork script that I have added to tag that onto the end of the URL counts as a refresh when it did not before, making this tweak no longer work on the homescreen. I am requesting that a small change of adding [youtube.com](url) to the pages this loads on, not just [youtube.com/feed/subscriptions](url)

**Comment by neiljdo** [comment]
My use case with be different but is addressed by the same feature being requested: Youtube still recommends already watched videos on my home page for some odd reason. I don't want to miss out on potentially interesting videos but the redundant recommendations clutter my home page.
