### ISSUE TITLE
Hiding watched hides all content on some channels

### ISSUE THREAD

**Issue by devtholt** [OsaSoft/youtube-better-subscriptions#85]
If I choose to hide watched videos on the subscriptions page and go to a content creators channel with the option still selected, nothing is shown below the **Home | Video | Playlists | Community | Channels | About** headers.

**Comment by OsaSoft** [comment]
it seems unlikely this would be caused by this extension, as at the moment it is completely inactive on channel pages.
Can you provide some more information?

**Comment by devtholt** [comment]
A page I see the issue with is [Simone Giertz](https://www.youtube.com/c/simonegiertz/). I have all other extensions turned off. If I go to subscriptions and hide watched then click to a channel, the content on the page does not show up. If I refresh the page, the content shows up until I return to the subscriptions page and hide watched removes my watched videos again. The screenshot was taken after going to my subscriptions, hiding watched videos, then clicking to Simone's page.

![image](https://user-images.githubusercontent.com/44012640/103141562-0dfd9d80-4707-11eb-8c09-dfeac5f620a7.png)

**Comment by OsaSoft** [comment]
I see you are on the HOME page. The extension should be doing absolutely nothing on the channel HOME page, it only activates on the VIDEOS one. So this seems most likely like an unrelated issue
