### ISSUE TITLE
"Use YouTube™'s watched gauge" Settings doesn't save

### ISSUE THREAD

**Issue by bin101** [OsaSoft/youtube-better-subscriptions#90]
Title says everything

I tick the box, click save and close the settings page. On reopen the tick is gone.

**Comment by NondescreptUser** [comment]
I have the same issue. Using Vivaldi 3.62165 in Windows 7 Pro 64-bit.

**Comment by OsaSoft** [comment]
this is weird. Sou you set the setting on the settings page ` Use YouTube™'s watched gauge (red bar on bottom of thumbnail) to mark as watched. ` and afterwards, it doesn work? Ie. for videos that have the YT wathced bar, it doesnt set them as watched?

**Comment by bin101** [comment]
Sometimes it works and sometimes not. At least if I activate this setting, save and reload the settings page the setting is no more activated.

**Comment by bin101** [comment]
@OsaSoft 
I think this line does something very strange:
https://github.com/OsaSoft/youtube-better-subscriptions/blob/4a65eefee4b557667d27cb962f65d53cbe6bda16/pages/settings/settings.js#L36
