### ISSUE TITLE
Hide Watch toggle in UI is missing

### ISSUE THREAD

**Issue by MarcLaf** [OsaSoft/youtube-better-subscriptions#93]
Not sure what's causing it but I cannot see the toggle switch anymore. Clicking Hide Watched does hide/show videos.

Microsoft Edge 89.0.774.45

**Comment by OsaSoft** [comment]
i think it might be related to #92

**Comment by MarcLaf** [comment]
Okay cool, thanks for letting me know.

**Comment by OsaSoft** [comment]
Well, seems like that did not fix the issue, at least for me. Reopening for now.

**Comment by GriffinG1** [comment]
Would like to add on to this that it was showing up for me prior to v0.15.1, and now no longer displays.

**Comment by GlitchedCod** [comment]
Same for me but i use Opera so i'm not really the prior guy to save from this bug. This is sad because this is the only extension that had this features and i have 2 months of video to see !

**Comment by OsaSoft** [comment]
yes, this is still very much a bug and issue. Unfortunately Ive not had time yet to fix this :(

Sorry for the inconvenience, Ill try to get to it as soon as I can

**Comment by GlitchedCod** [comment]
Hmm... Now it works, i don't know if you have fixed that or YouTube roll back something.
Since i have 2 mounth of videos to go throught can you add also a ckeckmark on "This mounth" and after ?
Amaazing job btw and you are the only extension that does that this is just perfect for my usage !

**Comment by OsaSoft** [comment]
seems it just got unchecked in the settings for me 😂 and here i spent ages debugging it 😅

**Comment by MarcLaf** [comment]
I don't understand, I still just have the label (text, "Hide watched") but I still don't have the toggle slider to show whether or not it's engaged. Has this been removed? I don't have an option in settings to show the toggle slider.

**Comment by OsaSoft** [comment]
@MarcLaf toggle itself was an issue with YT renaming their toggle component. I assumed this was only for the entire button, so the toggle is #99, but now reading this correctly after such a long time I see that that one is a duplicate of this. 
Anyway, the issue is now resolved and will be rolling out in v 0.16.0 shortly

**Comment by MarcLaf** [comment]
Oh awesome! Sorry to reopen the thread (or if my original post wasn't clear
enough). Happy to see it finally fixed! I love this extension so much, it's
so handy. Appreciate the work you've put into it.

**Comment by OsaSoft** [comment]
Sorry it took me so long to fix this and that my dumb head didnt realize the actual issue you reported 😅 

Im glad you like the extension :)
