### ISSUE TITLE
Addon not work. 

### ISSUE THREAD

**Issue by p6002** [OsaSoft/youtube-better-subscriptions#98]
I still see watched videos. Even after selecting all options in settings.
Newest Firefox on MacOS.
In addition, subscription feed shows a random videos from a week ago and more. After a few refreshments return to normality.
Another 5 minutes of testing and does not load information on video.
Unfortunately, the plug-in makes too much problems. It is not refined.

**Comment by QGB** [comment]
also not work for me chrome desktop... 【mark all as watched】  clicking does not respond

**Comment by Morgan-6Freedom** [comment]
Doesn't work anymore

**Comment by OsaSoft** [comment]
Can you enable logging in the settings and then refresh the subscriptions page with developer console open (shift+ctrl+j or Option + ⌘ + J on mac) and post the resulting logs please?

**Comment by OsaSoft** [comment]
Closed for inactivity
